import { ReactNode } from "react";

type fallbackType = string | null;

interface RouteInfoType {
  /**
   * id: string - unique id generated by uuid v4
   */
  id: string;
  /**
   * routePath: string - path of current route   
   */
  routePath: string;
  /**
   * fallbackTo: string | null - if null, dont fallback to given path, else do
   */
  fallbackTo: fallbackType;
  /**
   * name: string - name of route, can be used in navbar
   */
  name: string;
  /**
   * isProtected: boolean - checks if a route is protected or not
   */
  isProtected: boolean,
  /**
   * isExact: boolean - checks if a route should be exact match or not
   */
  isExact: boolean,
  /**
   * routeComponent: ReactNode - the component to render for given route
   */
  routeComponent: ReactNode
}

export default RouteInfoType;
